# Generated by Django 4.1.4 on 2022-12-23 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlisted",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
