# Generated by Django 4.1.4 on 2022-12-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_listing_watchlisted_alter_listing_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="watchlisted",
            new_name="watchlist",
        ),
    ]
