# Generated by Django 4.1.4 on 2023-01-03 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_rename_watchlisted_listing_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
