# Generated by Django 4.1.4 on 2023-01-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_listing_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
