# Generated by Django 4.1.4 on 2023-01-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_rename_bid_listing_starting_bid_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="starting_bid",
            new_name="bid",
        ),
        migrations.AlterField(
            model_name="bid",
            name="bid",
            field=models.FloatField(),
        ),
    ]
