# Generated by Django 4.1.4 on 2023-01-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
