# Generated by Django 4.1.4 on 2023-01-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_post_like_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="like_count",
        ),
    ]
