# Generated by Django 4.1.4 on 2023-01-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="no_likes",
            field=models.IntegerField(default=0),
        ),
    ]
